base_url = "https://nathanrw.github.io"
title = "nathanrw"
compile_sass = true
build_search_index = false
theme = "no-style-please"
generate_feed = true


[markdown]
highlight_code = true

[extra]
author = "nathanrw"
